module.exports = {
  NO_DATA: (str) => `${str} doesn't exist!`,
  REQUIRED: (str) => `${str} is required!`,
  UPDATE_DATA: (str) => `${str} has been update successfully!`,
  DELETE_DATA: (str) => `${str} has been delete successfully!`,
  GET_DATA: (str) => `${str} has been get successfully!`,
  ADD_DATA: (str) => `${str} has been added successfully!`,
  DATA_EXIST: (str) => `${str} already exist!`,
  DEACTIVATED: (str) => `${str} is temporarily deactivated. Please contact the administrator for assistance!`,
  REGISTER: (str) => `${str} registered successfully!`,
  NOT_REGISTER: (str) => `${str} doesn't register!`,
  NO_FOUND: (str) => `${str} not found!`,
  FOUND: (str) => `${str} found!`,
  NOT_MATCH: (str) => `${str} doesn't match, please try again!`,
  MATCH: (str) => `${str} match, successfully!`,
  LOG_IN: `Login successfully!`,
  ROLE_NOT_ALLOWED: `You are not allowed to login!`,
  SOMETHING_WENT_TO_WRONG: "Something went to wrong, please try again later!",
  SENT: (str) => `${str} has been sent to your registered email!`,
  SENT_REQUEST: (str) => `${str} has been sent successfully!`,
  INVALID: (str) => `Invalid ${str} !`,
  EXPIRED: (str) => `Your ${str} has expired. Try again with a new ${str}!`,
  NO_PROVIDE: (str) => `No ${str} provided!`,
  GENERATED: (str) => `${str} generated!`,
  UNAUTHORIZED: "Unauthorized!",
  CREATION_RESTRICTED: (str) => `${str} account creation is not permitted!`,
  INSUFFICIENT_BALANCE: "Insufficient balance to withdraw!",
  REQUEST_ALREADY_EXISTS: "You cannot submit a new request until your previous request is completed!",
  GARAGE_PENDING_REQUEST: "Your appointment request is still pending with the garage and has not been accepted yet!",
  GARAGE_NO_SERVICES_TAKEN: "You have not availed any services from this garage, so you cannot leave a review or feedback!",
  APPOINTMENT_COMPLETION_RESTRICTED: "The appointment status cannot be marked as completed by the garage. Only the customer or an admin can perform this action!",
  APPOINTMENT_ALREADY_COMPLETED: "This appointment is already completed, so you cannot suggest new services on it!",
  ALREADY_PAID: "The payment for this service has already been completed. No further transactions are required!",

  GET_LIST: (str) => `${str} list has been got successfully!`,
  NOT_UPDATE: (str) => `${str} doesn't updated!`,
  ADD_DATA: (str) => `${str} data has been added successfully!`,
  CREATE_FAILD: (str) => `${str} data add not successfully!`,
  PHONENO_EXIST: (str) => `${str} phone no already exists!`,
  EMAIL_EXIST: (str) => `${str} email already exists!`,
  DELETED_SUCCESS: (str) => `${str} deleted successfully!`,
  NOT_DELETED: (str) => `${str} not deleted!`,
  GET_DATA: (str) => `${str} has been got successfully!`,
  OCCUPIED: (str) => `${str} is already occupied!`,
  WITHOUT_PERMISSION: (str) => `${str} was taken without your permission. No purchase record was found!`,
  RECEIVED: (str) => `${str} received successfully!`,
};
